using assignment_19.Sealed;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace assignment_19.Partial
{
    //Auto generated by EF
    partial class Person : parent
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int? Age { get; set; }

        //no acces modifier , must be return void ,and no passign out pramaters
        partial void Print();
    }
}
